## 归一化

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = [[-1, 2], [-0.5, 6], [0,10], [1,18]]

In [ ]:
scaler = MinMaxScaler()
scaler.fit(X)

X_scaled = scaler.transform(X)

In [4]:
X_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [ ]:
# 还愿
X_returned = scaler.inverse_transform(X_scaled)
X_returned

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [ ]:
# 指定归一化的范围
scaler = MinMaxScaler(feature_range=(5, 10))

X_return_scaled = scaler.fit_transform(X_scaled)
X_return_scaled

array([[ 5.  ,  5.  ],
       [ 6.25,  6.25],
       [ 7.5 ,  7.5 ],
       [10.  , 10.  ]])

In [8]:
# 用Numpy
import numpy as np

In [9]:
X_array = np.array(X)
X_scaled_numpy = (X_array - X_array.min(axis=0)) / (X_array.max(axis=0) - X_array.min(axis=0))

X_scaled_numpy

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [1.  , 1.  ]])

In [48]:
X_array.max(axis=0)

array([ 1., 18.])

In [10]:
X_scaled_numpy * (X_array.max(axis=0) - X_array.min(axis=0))  + X_array.min(axis=0)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

### 标准化

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [23]:
scaler.mean_, scaler.var_

(array([-0.125,  9.   ]), array([ 0.546875, 35.      ]))

In [15]:
scaler.var_

array([ 0.546875, 35.      ])

In [16]:
X_standard = scaler.transform(X)
X_standard

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [17]:
X_standard.mean()

0.0

In [19]:
X_standard.std()

1.0

In [22]:
scaler.inverse_transform(X_standard)

array([[-1. ,  2. ],
       [-0.5,  6. ],
       [ 0. , 10. ],
       [ 1. , 18. ]])

In [24]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [25]:
data = pd.read_csv("Narrativedata.csv", index_col=0)
data.head()

,Age,Sex,Embarked,Survived
0,22.0,male,S,No
1,38.0,female,C,Yes
2,26.0,female,S,Yes
3,35.0,female,S,Yes
4,35.0,male,S,No


In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       714 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [38]:
# 实例化类
imp_mean = SimpleImputer()
imp_median = SimpleImputer(strategy="median")
imp_0 = SimpleImputer(strategy="constant", fill_value=0)

In [37]:
# 先填补age列
Age = data.loc[:, "Age"].values.reshape(-1,1)
Age.shape

(891, 1)

In [39]:
imp_mean = imp_mean.fit_transform(Age)
imp_median = imp_median.fit_transform(Age)
imp_0 = imp_0.fit_transform(Age)

In [41]:
data.loc[:, "Age"] = imp_median
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [42]:
embarked = SimpleImputer(strategy="most_frequent")
embarked.fit_transform(data.loc[:, "Embarked"].values.reshape(-1,1))

embarked

SimpleImputer(strategy='most_frequent')

In [43]:
data.loc[:, "Embarked"] = embarked
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [44]:
# numpy
data_ = pd.read_csv("Narrativedata.csv", index_col=0)

In [45]:
data_.loc[:, "Age"] = data_.loc[:, "Age"].fillna(data_.loc[:, "Age"].median())
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       891 non-null    float64
 1   Sex       891 non-null    object 
 2   Embarked  891 non-null    object 
 3   Survived  891 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.8+ KB


In [46]:
data_.dropna(axis=0, inplace=True)

In [47]:
data_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       889 non-null    float64
 1   Sex       889 non-null    object 
 2   Embarked  889 non-null    object 
 3   Survived  889 non-null    object 
dtypes: float64(1), object(3)
memory usage: 34.7+ KB


In [50]:
data_.head()

,Age,Sex,Embarked,Survived
0,22.0,male,S,No
1,38.0,female,C,Yes
2,26.0,female,S,Yes
3,35.0,female,S,Yes
4,35.0,male,S,No


### 编码

In [49]:
from sklearn.preprocessing import LabelEncoder

In [51]:
X_copy = data_.copy()

In [53]:
# 标签的编码
y = X_copy.iloc[:, -1]

le = LabelEncoder()
le.fit(y)
label = le.transform(y)

le.classes_

array(['No', 'Unknown', 'Yes'], dtype=object)

In [54]:
le.inverse_transform(label)

array(['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'Unknown', 'Yes', 'No', 'No', 'No', 'Unknown', 'No', 'Yes', 'No',
       'Yes', 'Unknown', 'Yes', 'Yes', 'Yes', 'No', 'Unknown', 'No', 'No',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'No', 'No', 'No', 'Unknown', 'Yes', 'No', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'No', 'No', 'No', 'No', 'Yes', 'Unknown', 'No', 'Unknown',
       'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Unknown', 'Yes',
       'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No', 'No',
       'No', 'No', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Unknown', 'No', 'No', 'Yes', 'No', 'No', 'Ye

In [ ]:
# 取的时sex 和 embarked 列
X_copy.iloc[:, -1] = label
X_copy.head()

,Age,Sex,Embarked,Survived
0,22.0,male,S,0
1,38.0,female,C,2
2,26.0,female,S,2
3,35.0,female,S,2
4,35.0,male,S,0


---

In [79]:
# 分类特征编码为分类数值
from sklearn.preprocessing import OrdinalEncoder

In [80]:
X_copy.head()

,Age,Sex,Embarked,Survived
0,22.0,male,S,0
1,38.0,female,C,2
2,26.0,female,S,2
3,35.0,female,S,2
4,35.0,male,S,0


In [81]:
X_copy_ordinal = X_copy.copy()

In [ ]:
# fit后可以查看每个特征有多少类
OrdinalEncoder().fit(X_copy_ordinal.iloc[:, 1:-1]).categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

In [84]:
# 取出特征列，用ordinal编码
X_copy_ordinal.iloc[:, 1:-1] = OrdinalEncoder().fit_transform(X_copy_ordinal.iloc[:, 1:-1])

In [85]:
X_copy_ordinal.head()

,Age,Sex,Embarked,Survived
0,22.0,1.0,2.0,0
1,38.0,0.0,0.0,2
2,26.0,0.0,2.0,2
3,35.0,0.0,2.0,2
4,35.0,1.0,2.0,0


因此所有的特征都编码为了数字类型

但这种编码方式无法表达变量之间的关系

In [56]:
from sklearn.preprocessing import OneHotEncoder

In [57]:
x = X_copy.iloc[:, 1:-1]

In [58]:
enc = OneHotEncoder(categories="auto").fit(x)
result = enc.transform(x)
result

<889x5 sparse matrix of type '<class 'numpy.float64'>'
	with 1778 stored elements in Compressed Sparse Row format>

In [59]:
# 可以发现将特征列OneHot编码后得到一个稀疏矩阵，一共5列，表示总的特征类别之和
# 转为array
result.toarray()

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [60]:
pd.DataFrame(enc.inverse_transform(result))

,0,1
0,male,S
1,female,C
2,female,S
3,female,S
4,male,S
...,...,...
884,male,S
885,female,S
886,female,S
887,male,C


In [62]:
# 放入特征矩阵中，并且去掉原来的特征列
X_copy_onehot = pd.concat([X_copy, pd.DataFrame(result.toarray())], axis=1)
X_copy_onehot.head()

,Age,Sex,Embarked,Survived,0,1,2,3,4
0,22.0,male,S,0,0.0,1.0,0.0,0.0,1.0
1,38.0,female,C,2,1.0,0.0,1.0,0.0,0.0
2,26.0,female,S,2,1.0,0.0,0.0,0.0,1.0
3,35.0,female,S,2,1.0,0.0,0.0,0.0,1.0
4,35.0,male,S,0,0.0,1.0,0.0,0.0,1.0


In [69]:
# 查看每个维度对应的特征取值
enc.get_feature_names_out()

array(['Sex_female', 'Sex_male', 'Embarked_C', 'Embarked_Q', 'Embarked_S'],
      dtype=object)

In [75]:
X_copy_onehot.drop(["Sex", "Embarked"], axis=1, inplace=True)
X_copy_onehot.head()

,Age,Survived,0,1,2,3,4
0,22.0,0,0.0,1.0,0.0,0.0,1.0
1,38.0,2,1.0,0.0,1.0,0.0,0.0
2,26.0,2,1.0,0.0,0.0,0.0,1.0
3,35.0,2,1.0,0.0,0.0,0.0,1.0
4,35.0,0,0.0,1.0,0.0,0.0,1.0


In [78]:
newX = X_copy_onehot.copy()
newX.columns = ["Age", "Survived", "Female", "Male", "C", "Q", "S"]
newX.head()

,Age,Survived,Female,Male,C,Q,S
0,22.0,0,0.0,1.0,0.0,0.0,1.0
1,38.0,2,1.0,0.0,1.0,0.0,0.0
2,26.0,2,1.0,0.0,0.0,0.0,1.0
3,35.0,2,1.0,0.0,0.0,0.0,1.0
4,35.0,0,0.0,1.0,0.0,0.0,1.0
